version: 2

project_name: portman

before:
  hooks:
    - go mod tidy

builds:
  - id: portman
    binary: portman
    main: ./cmd/portman
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/tasnimzotder/portman/internal/cli.Version={{.Version}}
      - -X github.com/tasnimzotder/portman/internal/cli.Commit={{.Commit}}
      - -X github.com/tasnimzotder/portman/internal/cli.Date={{.Date}}

archives:
  - id: portman
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

homebrew_casks:
  - repository:
      owner: tasnimzotder
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/tasnimzotder/portman"
    description: "See what's using your ports. Kill rogue processes. Wait for services."
    license: "MIT"
    binaries:
      - portman
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/portman"]

release:
  github:
    owner: tasnimzotder
    name: portman
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
